### ISSUE TITLE
Result from EatNow Server is different from that from foursquare

### ISSUE THREAD

**Issue by callzhang** [callzhang/EatNow#18]
![image](https://cloud.githubusercontent.com/assets/5102827/7060040/e5de794c-de47-11e4-9998-33f86fe54188.png)
![image](https://cloud.githubusercontent.com/assets/5102827/7060043/eb9b0a1c-de47-11e4-9db1-d17e12ea56d5.png)

**Comment by qitang** [comment]
Unable to reproduce the issue. Leave it open for now

**Comment by callzhang** [comment]
Any updates?

**Comment by qitang** [comment]
Fixed.
