### ISSUE TITLE
Missing url

### ISSUE THREAD

**Issue by callzhang** [callzhang/EatNow#22]
[;[fg255,127,0;2015-04-13 01:08:55:540 EatNow[1163:807] Request restaurant: {
   latitude = "22.284681";
   longitude = "114.158177";
   radius = 500;
   username = "E957F7C9-C185-4EBD-B6C6-EDD0265DAD0F";
}

[;[fg255,0,0;2015-04-13 01:09:07:625 EatNow[1163:807] Restaurant missing url Restaurant: Tim Ho Wan 添好運, rating: 8.3, reviews: 362, cuisine: Dim Sum, price： $, distance: 0.0km
[;[fg255,0,0;2015-04-13 01:09:07:626 EatNow[1163:807] Restaurant missing url Restaurant: Crystal Jade 翡翠拉麵小籠包, rating: 7.6, reviews: 154, cuisine: Dim Sum, price： $$, distance: 0.0km
[;[fg255,0,0;2015-04-13 01:09:07:627 EatNow[1163:807] Restaurant missing url Restaurant: Yat Lok Restaurant 一樂燒鵝, rating: 9.1, reviews: 115, cuisine: Asian, price： $$, distance: 0.4km
[;[fg255,0,0;2015-04-13 01:09:07:628 EatNow[1163:807] Restaurant missing url Restaurant: Butao Ramen 豚王, rating: 8.5, reviews: 118, cuisine: Ramen / Noodles, price： $, distance: 0.4km
[;[fg255,0,0;2015-04-13 01:09:07:629 EatNow[1163:807] Restaurant missing url Restaurant: Wing Lok Yuen Restaurant 永樂園餐廳, rating: 8.1, reviews: 20, cuisine: Restaurant, price： $$, distance: 0.3km
[;[fg255,0,0;2015-04-13 01:09:07:630 EatNow[1163:807] Restaurant missing url Restaurant: Sushi Kuu 壽司喰, rating: 8.5, reviews: 89, cuisine: Sushi, price： $$, distance: 0.5km
[;[fg255,0,0;2015-04-13 01:09:07:630 EatNow[1163:807] Restaurant missing price Restaurant: Lung King Heen 龍景軒, rating: 8.2, reviews: 103, cuisine: Cantonese, price： , distance: 0.2km
[;[fg255,0,0;2015-04-13 01:09:07:631 EatNow[1163:807] Restaurant missing url Restaurant: Cuisine Cuisine 國金軒, rating: 7.9, reviews: 24, cuisine: Chinese, price： $, distance: 0.1km
[;[fg255,0,0;2015-04-13 01:09:07:632 EatNow[1163:807] Restaurant missing url Restaurant: Ser Wong Fun 蛇王芬, rating: 8.3, reviews: 43, cuisine: Chinese, price： $, distance: 0.4km
[;[fg255,0,0;2015-04-13 01:09:07:632 EatNow[1163:807] Restaurant missing url Restaurant: Island Tang 港島廳, rating: 8.4, reviews: 35, cuisine: Chinese, price： $, distance: 0.5km
[;[fg255,0,0;2015-04-13 01:09:07:634 EatNow[1163:807] Restaurant missing url Restaurant: Sift Patisserie, rating: 8.1, reviews: 17, cuisine: Cupcakes, price： $$, distance: 0.4km
[;[fg255,0,0;2015-04-13 01:09:07:635 EatNow[1163:807] Restaurant missing url Restaurant: Nam Kee 南記粉麵, rating: 8.0, reviews: 20, cuisine: Ramen / Noodles, price： $, distance: 0.4km
[;[fg255,0,0;2015-04-13 01:09:07:635 EatNow[1163:807] Restaurant missing url Restaurant: Ore-no Kappou 俺の割烹, rating: 8.6, reviews: 6, cuisine: Japanese, price： $$, distance: 0.5km

**Comment by callzhang** [comment]
应该是没有餐厅的url吧，和前一个问题#21是一起的，如果确认不是我们的问题，就close

**Comment by qitang** [comment]
The restaurants may not have url in the result from Foursquare api. Issue closed
