### ISSUE TITLE
restaurant undefined when "selecting" a restaurant

### ISSUE THREAD

**Issue by callzhang** [callzhang/EatNow#24]
![image](https://cloud.githubusercontent.com/assets/5102827/7125833/4fcd6080-e202-11e4-8a7f-cc7291488e46.png)

**Comment by qitang** [comment]
can you show me the restaurant id you are posting?

**Comment by callzhang** [comment]
search结果里面随便找一个都不行
比如
42f15a80f964a520bb261fe3

**Comment by qitang** [comment]
please use restaurantId as the field name instead of restaurant
