### ISSUE TITLE
history需要的是restaurant的所有信息，和吃的时间

### ISSUE THREAD

**Issue by callzhang** [callzhang/EatNow#3]
history 还是不对，需要的是restaurant的所有信息，和吃的时间
比如餐厅的名字，图片等等都是需要的，对不对

**Comment by callzhang** [comment]
需要保存的restaurant属性：
Name	Type	Definition
id	string	Yelp ID for this business
is_claimed	bool	Whether business has been claimed by a business owner
is_closed	bool	Whether business has been (permanently) closed
name	string	Name of this business
image_url	string	URL of photo for this business
url	string	URL for business page on Yelp
mobile_url	string	URL for mobile business page on Yelp
phone	string	Phone number for this business with international dialing code (e.g. +442079460000)
display_phone	string	Phone number for this business formatted for display
review_count	number	Number of reviews for this business
categories	list	Provides a list of category name, alias pairs that this business is associated with. 
rating	number	Rating for this business (value ranges from 1, 1.5, ... 4.5, 5)
snippet_text	string	Snippet text associated with this business
location	dict	Location data for this business：需要location的所有属性，作为导航信息
menu_provider	string	Provider of the menu for this business
menu_date_updated	number	Last time this menu was updated on Yelp (Unix timestamp)
reviews	list	Contains one review associated with business：需要保存review的所有信息，将来可能有用，可以吗？

**Comment by qitang** [comment]
我吧之前所有的user 记录都删掉了， 因为现在用的 新的user schema，user history 只存 restaurant的 一个 reference了

**Comment by callzhang** [comment]
好的
