### ISSUE TITLE
Change the return type of "Select" API

### ISSUE THREAD

**Issue by callzhang** [callzhang/EatNow#36]
Currently the return type of select is html
![image](https://cloud.githubusercontent.com/assets/5102827/7190251/b392c310-e452-11e4-8bc8-dffe70cb5552.png)

Please change the response to json for consistency and easier client code implementation.

**Comment by qitang** [comment]
so I will send a 200 ok instead of the string. Is that ok?

**Comment by callzhang** [comment]
Can you return the user object? So that I don't have to query again.

**Comment by qitang** [comment]
fixed
