### ISSUE TITLE
User not defined in Select

### ISSUE THREAD

**Issue by callzhang** [callzhang/EatNow#38]
{
  "username": "lei",
  "restaurantId": "4b0c24fef964a520be3723e3",
  "like": "1",
  "latitude": "1",
  "longitude": "2",
  "distance": "100"
}

![image](https://cloud.githubusercontent.com/assets/5102827/7213937/1a257a48-e55f-11e4-855d-fa4a872908ce.png)

**Comment by callzhang** [comment]
Also, when selecting with real undefined user, the server crash
![image](https://cloud.githubusercontent.com/assets/5102827/7213950/95162b6c-e55f-11e4-887e-0fc93a9c9029.png)

**Comment by qitang** [comment]
can not reproduce the issue. Closed
