### ISSUE TITLE
半径不对

### ISSUE THREAD

**Issue by callzhang** [callzhang/EatNow#5]
2015-02-14 18:47:24.158 EatNow[18624:652120] Request: {
   latitude = "37.33259551999998";
   longitude = "-122.03031802";
   username = "5DAC04B7-7ADB-423A-9DC8-7FEF814568EF";
}

lei [10:57 PM]
返回结果只有三个

lei [10:57 PM]10:57
是不是半径不对

lei [10:58 PM]
你有什么好的建议？

**Comment by qitang** [comment]
半径是对的，目前是 500米半径， 我改成1500米之后，返回的结果就有40个了

**Comment by callzhang** [comment]
我们需要讨论一下半径范围的问题，你怎么看

**Comment by callzhang** [comment]
现在半径问题用一个fall back机制如何？
1. 先用500米半径
2. 如果返回结果小于40个，或者那就用1500米半径，不行就用更大的，10K米

**Comment by callzhang** [comment]
yelp搜索是否可以按照rating排序？

**Comment by qitang** [comment]
当前的40个结果就是 yelp rating 排序后得40个结果，然后我们在那个基础上又重新排序了
