### ISSUE TITLE
missing image url

### ISSUE THREAD

**Issue by callzhang** [callzhang/EatNow#6]
http://m.yelp.com/biz/fire-and-oak-jersey-city

**Comment by callzhang** [comment]
[fg255,0,0;2015-02-16 16:24:49:207 EatNow[22688:807] Restaurant missing image Restaurant: Fire & Oak, rating: 3.5, reviews: 189, cuisine: American (New), price： $$, distance: 0.3km
[;[fg255,0,0;2015-02-16 16:24:49:226 EatNow[22688:807] Restaurant missing image Restaurant: Fresca Deli, rating: 3.0, reviews: 3, cuisine: Delis, Grocery, price： $$, distance: 0.0km
[;[fg255,0,0;2015-02-16 16:24:49:228 EatNow[22688:807] Restaurant missing image Restaurant: Skylark On the Hudson, rating: 3.0, reviews: 180, cuisine: American (New), Diners, Bars, price： $$, distance: 0.0km
[;[fg255,0,0;2015-02-16 16:24:49:230 EatNow[22688:807] Restaurant missing image Restaurant: Confucius Asian Bistro, rating: 3.0, reviews: 140, cuisine: Chinese, Asian Fusion, price： $$, distance: 0.2km
[;[fg255,0,0;2015-02-16 16:24:49:232 EatNow[22688:807] Restaurant missing image Restaurant: Banana Leaf, rating: 2.5, reviews: 3, cuisine: Food Stands, price： $$, distance: 0.1km
[;[fg255,0,0;2015-02-16 16:24:49:234 EatNow[22688:807] Restaurant missing image Restaurant: Babo Teahouse, rating: 3.0, reviews: 127, cuisine: Asian Fusion, Coffee & Tea, Bubble Tea, price： $$, distance: 0.1km

**Comment by qitang** [comment]
its working with four square api
