### ISSUE TITLE
Update price score formular

### ISSUE THREAD

**Issue by callzhang** [callzhang/EatNow#8]
Using average user price
For user with no history, use 3 as average price
Update user statistics (ave. price, ave. distance, ave. rating) every time when user selects a restaurant

**Comment by justfinish** [comment]
It should be 2.5 instead of 3 since the max is 4.

—
Lance

**Comment by callzhang** [comment]
@stealop Please follow @justfinish 's suggest, using 2.5 as initial ave price

**Comment by callzhang** [comment]
@stealop ?

**Comment by qitang** [comment]
used 2.2 as the initial average price as in the document

**Comment by qitang** [comment]
issues fixed

**Comment by callzhang** [comment]
2.2 is the average user price, it's not a static value

**Comment by qitang** [comment]
as stated in the issue, when there is no history for the user, use 2.2 as default average price

**Comment by callzhang** [comment]
2.2是用户的平均价格，如果为空，用2.5，基本sense啊！

**Comment by qitang** [comment]
now using 2.5 as default average price
